FROM python:3.11-slim
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
COPY pyproject.toml .
RUN uv sync --frozen
COPY . .
CMD ["uv", "run", "fastapi", "run", "app/main.py", "--port", "8000"]